# Site
name: 'Participation citoyenne'
description: 'Le blog de la participation citoyenne.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'participation-citoyenne'
email: 'contact@copas.coop'
mailchimp-list: 'https://copas.us11.list-manage.com/subscribe/post?u=59e9723432d697c47ea2ae93f&amp;id=311766f712'
timezone: Europe/Paris

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    aubry:
      name:           Aubry
      site:           http://www.copas.coop/aubry_prieur.html
      avatar:         assets/images/avatar1.jpg
      bio:            "C'est moi"
      email:          aubry.prieur@copas.coop
      twitter:        https://www.linkedin.com/in/aubry-prieur

    samuel:
      name:           Samuel
      site:           http://www.copas.coop/samuel-thyrion.html
      avatar:         assets/images/avatar1.jpg
      bio:            "C'est Samuel"
      email:          samuel.thyrion@copas.coop
      twitter:        https://www.linkedin.com/in/samuel-thyrion-1a057495

    said:
      name:           Saïd
      site:           http://www.copas.coop/said-bechrouri.html
      avatar:         assets/images/avatar1.jpg
      bio:            "C'est Saïd"
      email:          said.bechrouri@copas.coop
      twitter:        https://www.linkedin.com/in/saïd-bechrouri-9bb4335

    dalila:
      name:           Dalila
      site:           http://www.copas.coop/Dalila_Bahmed.html
      avatar:         assets/images/avatar2.jpg
      bio:            "C'est Dalila"
      email:          dalila.bahmed@copas.coop
      twitter:        https://www.linkedin.com/in/dalila-bahmed-348540116

    gilles:
      name:           Gilles
      site:           http://www.copas.coop/gilles-rivet.html
      avatar:         assets/images/avatar1.jpg
      bio:            "C'est Gilles"
      email:          gilles.rivet@copas.coop
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: aubry
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
