# Site
name: 'Participation citoyenne'
description: 'Le blog de la participation citoyenne.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog-participation-citoyenne'
disqus: 'participation-citoyenne'
email: 'contact@copas.coop'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
timezone: Europe/Paris

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    aubry:
      name:           Aubry
      site:           https://www.copas.coop
      avatar:         /assets/images/avatar1.jpg
      bio:            "Bonjour, je suis Aubry"
      email:          contact@copas.coop
      twitter:        https://twitter.com/aubryprieur

    samuel:
      name:           Samuel
      site:           https://www.copas.coop
      avatar:         /assets/images/avatar1.jpg
      bio:            "C'est Samuel"
      email:          samuel.thyrion@copas.coop
      twitter:        https://twitter.com/wowthemesnet

    said:
      name:           Saïd
      site:           https://www.copas.coop
      avatar:         /assets/images/avatar1.jpg
      bio:            "C'est Saïd"
      email:          said.bechrouri@copas.coop
      twitter:        https://twitter.com/wowthemesnet

    dalila:
      name:           Dalila
      site:           https://www.copas.coop
      avatar:         /assets/images/avatar2.jpg
      bio:            "C'est Dalila"
      email:          Dalila.bahmed@copas.coop
      twitter:        https://twitter.com/wowthemesnet

    gilles:
      name:           Gilles
      site:           https://www.copas.coop
      avatar:         /assets/images/avatar1.jpg
      bio:            "C'est Gilles"
      email:          gilles.rivet@copas.coop
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: aubry
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
